# Generated by Django 3.0.8 on 2020-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20200727_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='count_entries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
