# Generated by Django 3.0.8 on 2020-08-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_topic_count_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.TextField(default='Статья'),
        ),
    ]
