# Generated by Django 3.0.8 on 2020-08-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_entry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
